### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by udayms** [MShekow/outlook-google-calendar-sync#2]
Love this Flow. It works as described and is simple to configure. I use it to sync my work calendar with my family google calendar. Helps with sharing my availability with my family members. I do have one feature request. Is there a way to make the text BLOCKER configurable during setup? I managed to do it by editing the definitions.json file. But, I think it would be a good configurable option for everyone.

**Comment by MShekow** [comment]
Hey, Glad the flow helps you. Unfortunately, I'm not sure what you mean. The term "BLOCKER" does not appear in the flow at all. There is a Sync Blocker _Prefix_ variable at the top, no idea if you mean that?

**Comment by udayms** [comment]
There are two instances of `concat(variables('syncBlockerEventName'),'Blocker')` in the definition.json file. 

If I hide the event details in Calendar 2 (Google) in the configuration steps, the created Event title is being set to **Blocker**. By changing this text to something shorter like 'Wrk', helps keep the calendar cleaner.

**Comment by MShekow** [comment]
Ah ok, now I got it. Thanks for reporting it, once I work on the next version I'll include it.
