### ISSUE TITLE
Selectively display event details

### ISSUE THREAD

**Issue by udayms** [MShekow/outlook-google-calendar-sync#5]
After using this Sync for a couple of weeks, I have one more feature request. I don't know if other users would appreciate this, but I'm adding it here so that I can get some ideas for working around this without changing the original flow.

Connected to the Hide Event Details feature, can we check for a specific category on the event?

Use Case: I use my work calendar (Office 365 Outlook) for all my professional and personal events, reminders, and meetings. I also use this Sync to copy the events to my personal Google calendar. I hide the details of the events as I don't want to expose work events to my personal calendar (or break some IT security policy by doing so). So, all my work events are displayed in my personal calendar as `Busy`. When I add personal events to my work calendar (Like a dentist appt), I want those event details to be displayed on my Google calendar. This way, anyone accessing my personal calendar would see the details of personal events, but work event details would not be visible.

Suggestion: We could base this on the event category. If the category of an event matches a keyword that the user defines in the configuration of the flow, then copy over the event details along with the event. If not, replace it with the configured generic text.

**Comment by MShekow** [comment]
Thanks for the request, it looks reasonable 👍
