### ISSUE TITLE
Issue syncing multiple Google Calendars to a single Outlook calendar

### ISSUE THREAD

**Issue by HaydenS3** [MShekow/outlook-google-calendar-sync#8]
When syncing multiple Google Calendats to a single Outlook calendar. One Google Calendar's flow will overwrite the work done by a previous Google Calendar's flow.

**Comment by HaydenS3** [comment]
Downgrading to v0.8 and changing the event prefix for each flow seems to have fixed the issue. I think the issue in v0.9 has to do with SyncBlocker tracking events via the attendee.

**Comment by MShekow** [comment]
Thanks for the issue report. I was already aware of this issue (it happened to users that use the Outlook <-> Outlook [flow](https://github.com/MShekow/outlook-calendar-sync)), and I've now [updated](https://github.com/MShekow/outlook-google-calendar-sync/commit/f2291050656690d1ffe475a6252033b589202a09) the README to document this limitation.
